language: node_js
script:
- yarn run test
- yarn run lint
node_js:
- 6
- 7
deploy:
  provider: npm
  email: jesse_gibson@me.com
  api_key:
    secure: GCbepsOech7ND8/bHrbF6mSi6hkLXDMggAdJV8WGL05+FashjX5hqsOOK9xbIIOFS7Nhks1wmvNrGbiTaWscmRkG5FXNjJC/+m8yNmaNgQ6dQysw7R3pjthK8jfvxlQfj1aY8fpR9u+A/TYhr1/BX/Y65bD5LxNTmO5zBzUosh7JHL8XcoKZQDA35BkvZIGHijxGPf6JWeA35ykmSYI2SsvLyZwL3iJ1e/7xhMAlVTWQD+dK2JacSTf0hjeujVJ5EDqgQFn8J6DsMRzs2dW2UbM9hkgwpm+Pt+fOIpDfXIU/W6+O7SBAxr7Etm+8x6O6/CXsJo/sa/in7cWtsNolPye01FdeMKQd4ATKvifx0gKKnxnMuVWlDDQLIwhdfeafmiHfIJTLPEIZfvWRl72XzpXKlYsQEfutiJ4RLE8V4T50Eyw9FDiwUBLR6Cq0aMe0oFn1oHoQ9ltY05OPk9gS3APDRyHlaxUl2Y0R34g4nHvnwBot4OefkEtWUYdUFRzg+rSSEJoRkm8gr/r+9r0UvdqVtBkDsLnk6yvTIw+dKnp0ig6iz39QRHQRH6Ni4Vp+m4CoUdwkylpkdvere87HMBUzuaiGklDnnCdmsrN1W8CauL7YEl1OhKb+wnuRYF7iJzqPUZmBmTx8tY1ZkiAQoBzid8VrNJt6GvfDIxPPXp4=
  on:
    tags: true
    repo: PsychoLlama/expect-enzyme
